---
name: Pull Request Labeler

on:  # yamllint disable-line rule:truthy
  # note: security risk from this action.  Do not add
  # actions in here which need a checkout of the repo,
  # and do not use any caching in here.
  pull_request_target:

jobs:
  autolabel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: TimonVS/pr-labeler-action@v3.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
