---
name: CI
# should eventually be "on release created"
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  autorelease:
    name: Helm autorelease
    runs-on: ubuntu-latest
    env:
      DEV_VAL_FILE: charts/values-dev.yaml
    steps:
    - name: helm checkout
      uses: actions/checkout@v2.3.4
      with:
        repository: ${{ secrets.HELM_REPOSITORY }} # should be "user/repo" format
        ssh-key: ${{ secrets.HELM_DEPLOY_KEY }}
    - name: get lastest release
      id: latestrelease
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: ${{ github.repository }}
        excludes: prerelease, draft
    - name: set tag & branch name for future runs
      run: |
        TAG=${{ steps.latestrelease.outputs.release }}
        {
          printf "TAG=$TAG\n"
          printf "BRANCH=autorelease/bump-docker-$TAG\n"
        } >> $GITHUB_ENV

    - name: enable ssh agent
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.HELM_DEPLOY_KEY }}
    - name: git branch setup
      run: |
        git config --local user.name "$GITHUB_REPOSITORY"
        git config --local user.email github-actions@github.com
        git checkout -b "$BRANCH"
    - name: pre-commit setup
      run: |
        pip install pre-commit
        pre-commit install-hooks

    - name: helm update YAML
      uses: devorbitus/yq-action-output@v1.1
      with:
        cmd: yq --inplace eval '.["api", "content", "resource-manager", "worker"].image.tag = env(TAG)' '${{ env.DEV_VAL_FILE }}'
    - name: reformat YAML with pre-commit
      run: |
        # first run fails if it needs to reformat, so run twice if first fails
        pre-commit run yamlfmt --files "$DEV_VAL_FILE" \
        || pre-commit run yamlfmt --files "$DEV_VAL_FILE"
    # might be able to use actions/checkout for push instead of the ssh agent
    # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
    - name: helm commit
      run: |
        git add "$DEV_VAL_FILE"
        git commit -m "Bump dev image to $TAG"
        git push --set-upstream origin "$BRANCH"
